#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT 1

#define FORCE_NKRO
#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_COUNT 3
#define COMBO_TERM 150

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
